server:
  port: 8811
spring:
  datasource:
    url : ${MYSQL_URL:jdbc:mysql://localhost:3306/userdb}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:admin}
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
